# Generated by Django 3.2.5 on 2021-12-25 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_class_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/class_imgs', verbose_name='Image')),
                ('image_name', models.CharField(max_length=350, verbose_name='Image name')),
                ('related_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class', verbose_name='Related class')),
            ],
            options={
                'verbose_name': 'Class image',
                'verbose_name_plural': 'Class images',
            },
        ),
    ]
