# Generated by Django 3.2.5 on 2021-12-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=350, verbose_name='Image name')),
                ('image', models.ImageField(upload_to='uploads/gallery_imgs', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Gallery image',
                'verbose_name_plural': 'Gallery images',
            },
        ),
    ]
