# Generated by Django 3.2.5 on 2021-12-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=350, verbose_name='Teacher name')),
                ('teacher_photo', models.ImageField(upload_to='uploads/teachers_photos', verbose_name='Teacher photo')),
                ('teacher_degree', models.CharField(max_length=350, verbose_name='Teacher degree')),
                ('teacher_experience', models.CharField(max_length=350, verbose_name='Teacher experience')),
                ('teacher_hobbies', models.CharField(max_length=350, verbose_name='Teacher hobbies')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
    ]
