# Generated by Django 3.2.5 on 2021-12-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_bio',
            field=models.TextField(default='teacher bio goes here', verbose_name='Teacher bio'),
            preserve_default=False,
        ),
    ]
